name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0", "3.2"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: StandardRb check
        run: bundle exec standardrb

      - name: Run tests
        run: |
          bundle exec rake test
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
